### PR TITLE
I've been working on the setting...

### PR DESCRIPTION
**Pull request by ihabunek**
...all the live long daaaayy

### CODE REVIEW

**Comment by robertbasic** [comment]
Also let me know when you're done with working on settings because it heavily clashes with my work on adding support for projects.

**Comment by ihabunek** [comment]
Ah, ok. I'll do this and let you work on projects then.

**Comment by robertbasic** [comment]
I decided to make projects simpler by just saving/loading settings (and loading in the defaults) :D

**Comment by robertbasic** [comment]
No need for hurry, I can work on other things until you finish up what you wanted.

**Comment by ihabunek** [comment]
I think I should add "Save" and "Cancel" buttons and save when the dialog closes. Wdyt?

**Comment by robertbasic** [comment]
In some format saving is already in there on my projects feature branch, so no need for it. These "projects" will actually just be a possibility to save settings under different "names", and load them up later on.

**Comment by robertbasic** [comment]
Actually nevermind the textChanged signal, that's probably going to be ripped out once settings save/load/apply is done.

**Comment by ihabunek** [comment]
Heh, ok. I actually have a mostly reworked settings model waiting, but maybe it's easier if you merge your stuff first.

**Comment by robertbasic** [comment]
Oh boy. Finish up all your ideas, everything you want to end up in the code, I'll merge them and figure out the rest of it from there.

**Comment by ihabunek** [comment]
Well, here it is. Have a look. :)

**Comment by robertbasic** [comment]
```
(env)robert@odin ~/pugdebug[feature/settings]$ python app.py 
Traceback (most recent call last):
  File "/home/robert/pugdebug/pugdebug/gui/settings.py", line 96, in showEvent
    self.load_settings()
  File "/home/robert/pugdebug/pugdebug/gui/settings.py", line 116, in load_settings
    self.set_widget_value(widget, value)
  File "/home/robert/pugdebug/pugdebug/gui/settings.py", line 144, in set_widget_value
    widget.setValue(value)
TypeError: QSpinBox.setValue(int): argument 1 has unexpected type 'str'
```

Other than that looks good.

**Comment by robertbasic** [comment]
Why the `utils.py`?

**Comment by ihabunek** [comment]
I thought it might make sense to remove it from settings.py since it's a very generic pair of methods. You'd rather minimize the number of files?

**Comment by ihabunek** [comment]
I cannot reproduce your problem. Somehow you got a string into the setting for a spinbox. I can fix it by casting the value to int when setting, but it shouldn't really happen.

**Comment by robertbasic** [comment]
No, I just consider a generic "utils.py", "functions.php", and the like as code smell. It tends to end up as a mess of code, so I'd like to avoid having those.

**Comment by robertbasic** [comment]
It's because on Linux the settings file is a regular text file, so everything is a string. Cast it to int.

**Comment by ihabunek** [comment]
Eh, i'll leave them in settings for now and we can extract when/if needed.

**Comment by ihabunek** [comment]
Done.

**Comment by ihabunek** [comment]
\o/

**Pull request merged**
