### PR TITLE
Implement a better layout

### PR DESCRIPTION
**Pull request by ihabunek**
Have the document viewer as a central widget, and other widgets as
QDockWidgets.

### CODE REVIEW

**Comment by ihabunek** [comment]
Try this out. It's a nice layout arrangable by drag and drop.

**Comment by robertbasic** [comment]
Hm, the file browser and settings in left dock area are ok, the rest of it I don't like that much. I know the current layout is horrible, but it's just a temporary solution while I get around to implementing the whole QMdiArea stuff http://doc.qt.io/qt-5/qmdiarea.html and then have the 4 different viewers as mdi sub windows which then allows the user to properly arrange the windows as they see fit, and eventually saving that as an application setting across application restarts.

**Comment by ihabunek** [comment]
Uh, not a fan of MDI. But it's your project. :)

This layout can also be rearranged. Dock windows on any of the 4 sides and have mulitple windows in one position as tabs. Settings can be saved quite easily using QSettings.

**Comment by robertbasic** [comment]
What's wrong with MDI?

I know they can be rearranged, but having the viewers as docks seems to me as they are a "2nd class citizen" like this, and only the code viewer is the "main" part here.

For example, the variable viewer is small and to the side with this, but this being a debugger only, the variable viewer is as important as the code viewer.

If this makes sense :)

**Comment by ihabunek** [comment]
The ones I used were just not very nice to use, hard to make them look the way I wanted. And would fall apart if I switched resolution (e.g. when docking a laptop).

I other news, I never tried Qt's MDI :) So I will reserve final judgement for when I see it in action.

**Comment by robertbasic** [comment]
screenshot - 04042015 - 06 27 54 pm

Here's a quick stab at mdi windows. Maybe additionally remove the title bar from the documents viewer.

**Comment by ihabunek** [comment]
Doesn't look bad. How well does it behave when resizing the main window?

**Comment by robertbasic** [comment]
Closing in favour of https://github.com/robertbasic/pugdebug/pull/28

**Pull request closed without merging**
